BEGIN;

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS wbs_code VARCHAR(50);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS parent_task_id INT REFERENCES tasks(id);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS color VARCHAR(20) DEFAULT '#378ADD';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS dependencies TEXT;

COMMIT;
